# docker-compose.yml

version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development

  ml:
    build: ./ML
    ports:
      - "5000:5000"
    volumes:
      - ./ML:/app
    environment:
      - PYTHONUNBUFFERED=1
